name: Setup Firebolt database and engine
description: >-
 Setup Firebolt database with the generated name. Then, setup an engine with the same
 name, which is attached to the created database
inputs:
  firebolt-username:
    description: Firebolt account username
    required: true
  firebolt-password:
    description: Firebolt account password
    required: true
  api-endpoint:
    description: Firebolt api address
    default: 'api.app.firebolt.io'
    required: false
  region:
    description: In which region to create the database
    default: 'us-east-1'
    required: false
  db_suffix:
    descriptiona: Suffix to add to db name
    default: ''
    required: false
    
outputs:
  database_name:
    description: Name of created database
  engine_name:
    description: Name of created engine
  engine_url:
    description: Endpoint of created engine
  stopped_engine_name:
    description: Name of created engine in stopped state
  stopped_engine_url:
    description: Endpoint of created engine in stopped state
        
runs:
  using: node12
  main: setup_bundle.js
  post: cleanup_bundle.js
